export { default as LandingNavbar } from './LandingNavbar';
export { default as HeroSection } from './HeroSection';
export { default as ScrollsAnimation } from './ScrollsAnimation';
export { default as Reveal } from './Reveal';
export { default as FeaturesSection } from './FeaturesSection';
export { default as HowItWorksSection } from './HowItWorksSection';
export { default as IdeaSection } from './IdeaSection';
export { default as CTASection } from './CTASection';
export { default as LandingFooter } from './LandingFooter';
